### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by Gengar-lab** [Esie-Eyen/BSMods#4]
@Esie-Eyen Have all my mods completed?

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen Can you Make a Powerup that if we take it our health would increase.

Another : If we took that powerup and die , the position where we died,  bombs would erupt from that place

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Please give your discord link.

**Comment by Mikahael** [comment]
> 
> 
> @Esie-Eyen Can you Make a Powerup that if we take it our health would increase.
 i could maybe make this one
