### ISSUE TITLE
files

### ISSUE THREAD

**Issue by Mikahael** [Esie-Eyen/BSMods#7]
Hey, I can fix your powerups and use them on my server. I will share it with others as well, mate.

**Comment by Esie-Eyen** [comment]
Sure, sorry for the late reply, have you already done it?

**Comment by Mikahael** [comment]
Done. Already in server.

**Comment by Mikahael** [comment]
It’s in bs ver 1.4 and 1.6

**Comment by Esie-Eyen** [comment]
Oh cool, I recently just got back to BombSquad after not playing for years.

Good to know someone use one of my mods.

**Comment by Mikahael** [comment]
Wow, hey, if you are still into modding, say so. I can help you :) bs modding has also gone well.

**Comment by Mikahael** [comment]
Yes brother, I’ll add you. Tell me your disc Id

**Comment by Mikahael** [comment]
Ok I’ll add you soon

**Comment by Mikahael** [comment]
While you on, check out my server files. https://github.com/Mikahael/PCModderServerFIles-FINAL

**Comment by Mikahael** [comment]
I have sent a friend req. accept it.
